### ISSUE TITLE
ErrorException [ 8192 ]: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead

### ISSUE THREAD

**Issue by tunayuyar** [tasuki/gallery#1]
Hi,

Im no expert on those things. 

Error is generated using PHP 5.5 on debian server. Could you help to fix this? It does not throw this error on every folder, I think it does on characters like "_" "ı"  etc.

I hope this info helps. 

Thanks.

Edit: Problem is not related with "_" character, I suppose Turkish characters like "ş, ı, ö, ç, ü, ..." creating this problem. Changing this characters seems to solve it.

**Comment by tasuki** [comment]
Can you please post the full stack trace? I'm not using the `/e` modifier anywhere, but the underlying framework might!

**Comment by tunayuyar** [comment]
@tasuk Hi,

I will try to produce problem again tomorrow and report here. Thanks for your reply.

**Comment by tasuki** [comment]
This is most definitely obsolete. The gallery is now written in Symfony.
